version: '3.9'

services:
  webhook:
    build: .
    container_name: alertwebhook
    ports:
      - "9094:9094"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    networks:
      - obs
    restart: unless-stopped
    environment:
      - DISCORD_WEBHOOK_URL=
      - TIMEZONE=Europe/Madrid

networks:
  obs:
    external: true

